### ISSUE TITLE
Oxygen OS 3.0.2 + Android N-ify

### ISSUE THREAD

**Issue by lapwat** [gavinhungry/Xposed-OnePlus-NoQsEditButton#1]
NoQS not working with this config

**Comment by gavinhungry** [comment]
Sorry, I don't have any OnePlus devices anymore. I've left the code up on GitHub for others to fork.

**Comment by lapwat** [comment]
Could you at least give me my payment back since the premium feature doesn't work ?
Thank you

**Comment by gavinhungry** [comment]
@KeNt178,

Um, what payment? This module is free and open source.

**Comment by lapwat** [comment]
Hmm, I'm sorry I picked the wrong application by mistake.
